export const STORE_INIT = 'STORE_INIT';
export const STORE_CONNECT_REACTOR = 'STORE_CONNECT_REACTOR';
export const REACTOR_START = 'REACTOR_START';
export const RECORD_EVENT_TIME = 'RECORD_EVENT_TIME';